services:
  - type: web
    name: customer-360-api
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.8
      - key: DATABASE_URL
        fromDatabase:
          name: customer-360-db
          property: connectionString

databases:
  - name: customer-360-db
    databaseName: customer360
    plan: basic-256mb
