"""Synthetic Northline book. Dates are relative so the demo stays current."""

STORY_ORDER = ["CUS-1042", "CUS-1107", "CUS-1088", "CUS-1214", "CUS-1003", "CUS-1175"]

CUSTOMERS = [
    {
        "id": "CUS-1042",
        "name": "Priya Nair",
        "age": 38,
        "city": "Chicago",
        "region": "Illinois",
        "occupation": "Product director",
        "email": "priya.nair@mail.example",
        "phone": "+1 (312) 555-0142",
        "segment": "Affluent",
        "book": "Insurance",
        "tenure_months": 76,
        "customer_value": 28600,
        "story_kicker": "High churn risk",
        "story_title": "Claim delay meets renewal",
        "story_blurb": "A negative call, an open hospital claim, and a renewal in 16 days.",
        "products": [
            {"kind": "Policy", "name": "Health Advantage", "number": "POL-55821", "status": "Active", "installment": 186, "frequency": "Monthly", "cover": 15000, "outstanding": 0, "renewal_in_days": 16, "started_days_ago": 1400, "pay": "monthly6"},
            {"kind": "Policy", "name": "Term Life 20", "number": "POL-55822", "status": "Active", "installment": 42, "frequency": "Monthly", "cover": 500000, "outstanding": 0, "renewal_in_days": 240, "started_days_ago": 900, "pay": "monthly6"},
        ],
        "cases": [
            {"id": "CLM-3391", "kind": "Claim", "title": "Hospital reimbursement still in review", "description": "Supplemental hospital claim for a three-day admission. Itemized bill and discharge summary are on file. Decision is still in review.", "status": "In Progress", "opened_days_ago": 24, "closed_days_ago": None, "amount": 6840, "product_index": 0},
        ],
        "interactions": [
            {"channel": "Call", "direction": "Inbound", "days_ago": 2, "agent": "Helena Ortiz", "subject": "Claim CLM-3391 and renewal", "duration_min": 14, "body": "I've been calling about claim CLM-3391 for three weeks. The hospital bill was $6,840 and your portal still says in review. I'm frustrated. My policy renews this month and honestly I'm looking at switching to another insurer if this isn't settled. I don't want a script. I want the reimbursement. This delay is unacceptable."},
            {"channel": "Email", "direction": "Inbound", "days_ago": 9, "agent": "Helena Ortiz", "subject": "Documents for CLM-3391", "duration_min": None, "body": "Attached are the discharge summary and the itemized bill for CLM-3391. The portal asked for a document I already sent. I'm still waiting on a straight answer. I need this closed before renewal."},
            {"channel": "Call", "direction": "Inbound", "days_ago": 55, "agent": "Jonah Reed", "subject": "Annual benefits check", "duration_min": 8, "body": "Thanks for the annual checkup call. The telehealth benefit has been useful and I'm happy with the plan overall. I only wanted to confirm the specialist copay."},
        ],
    },
    {
        "id": "CUS-1107",
        "name": "James Okonkwo",
        "age": 44,
        "city": "Atlanta",
        "region": "Georgia",
        "occupation": "High-school principal",
        "email": "james.okonkwo@mail.example",
        "phone": "+1 (404) 555-0177",
        "segment": "Retail",
        "book": "Insurance",
        "tenure_months": 49,
        "customer_value": 8400,
        "story_kicker": "Unresolved complaint",
        "story_title": "Partial denial, no plain-language explanation",
        "story_blurb": "Hail claim rental portion denied. Latest call is negative and still open.",
        "products": [
            {"kind": "Policy", "name": "Auto Comprehensive", "number": "POL-44102", "status": "Active", "installment": 146, "frequency": "Monthly", "cover": 300000, "outstanding": 0, "renewal_in_days": 140, "started_days_ago": 1200, "pay": "monthly6"},
        ],
        "cases": [
            {"id": "CLM-4410", "kind": "Claim", "title": "Hail damage — rental portion declined", "description": "Rental portion declined under the transportation exclusion. Customer disputes the explanation.", "status": "Denied", "opened_days_ago": 30, "closed_days_ago": 12, "amount": 420, "product_index": 0},
            {"id": "CMP-4411", "kind": "Complaint", "title": "Unexplained partial denial", "description": "Customer wants a supervisor to review the rental-car portion and a plain-language explanation of the exclusion.", "status": "Open", "opened_days_ago": 11, "closed_days_ago": None, "amount": 420, "product_index": 0},
        ],
        "interactions": [
            {"channel": "Call", "direction": "Inbound", "days_ago": 1, "agent": "Alicia Nguyen", "subject": "Complaint on the hail claim", "duration_min": 16, "body": "This is a complaint. You denied the rental-car portion of my hail claim after I had already paid the deductible. The adjuster was rude and nobody explained the exclusion in plain language. I want a supervisor. I'm not happy, and I will not recommend Northline until this is corrected."},
            {"channel": "Email", "direction": "Inbound", "days_ago": 6, "agent": "Alicia Nguyen", "subject": "Please log the supervisor request", "duration_min": None, "body": "Writing this down so it is on the file. I still want a supervisor to review the rental portion of claim CLM-4410. The phone explanation was not clear."},
        ],
    },
    {
        "id": "CUS-1088",
        "name": "Mei Chen",
        "age": 41,
        "city": "Seattle",
        "region": "Washington",
        "occupation": "Architect",
        "email": "mei.chen@mail.example",
        "phone": "+1 (206) 555-0134",
        "segment": "Affluent",
        "book": "Insurance",
        "tenure_months": 62,
        "customer_value": 19200,
        "story_kicker": "Upcoming renewal",
        "story_title": "Calm customer, cover needs an update",
        "story_blurb": "Homeowners renews in 21 days after a kitchen renovation. Sentiment is positive.",
        "products": [
            {"kind": "Policy", "name": "Homeowners", "number": "POL-77310", "status": "Active", "installment": 1860, "frequency": "Annual", "cover": 920000, "outstanding": 0, "renewal_in_days": 21, "started_days_ago": 1600, "pay": "annual2"},
            {"kind": "Policy", "name": "Term Life 20", "number": "POL-77311", "status": "Active", "installment": 64, "frequency": "Monthly", "cover": 750000, "outstanding": 0, "renewal_in_days": 220, "started_days_ago": 800, "pay": "monthly6"},
        ],
        "cases": [],
        "interactions": [
            {"channel": "Call", "direction": "Inbound", "days_ago": 4, "agent": "Samir Shah", "subject": "Homeowners renewal after renovation", "duration_min": 11, "body": "I'm calling because my homeowners policy renews next month. I'd like to review coverage after the kitchen renovation. Overall you've been great — the claim we had two years ago was paid quickly. Can you send renewal options with a higher dwelling limit?"},
            {"channel": "Email", "direction": "Inbound", "days_ago": 8, "agent": "Samir Shah", "subject": "Renewal options", "duration_min": None, "body": "Following up on renewal options for the kitchen renovation. No complaints, I just want the numbers before the renewal date."},
        ],
    },
    {
        "id": "CUS-1214",
        "name": "Arjun Mehta",
        "age": 36,
        "city": "Austin",
        "region": "Texas",
        "occupation": "Software engineering manager",
        "email": "arjun.mehta@mail.example",
        "phone": "+1 (512) 555-0194",
        "segment": "Retail",
        "book": "Lending",
        "tenure_months": 46,
        "customer_value": 31400,
        "story_kicker": "Cross-sell",
        "story_title": "Mortgage on the books, cover is not",
        "story_blurb": "Current home loan. He asked for a homeowners quote and said he is open on price.",
        "products": [
            {"kind": "Loan", "name": "Home mortgage", "number": "LN-19044", "status": "Active", "installment": 2480, "frequency": "Monthly", "cover": 0, "outstanding": 412000, "renewal_in_days": None, "started_days_ago": 1400, "pay": "monthly6"},
        ],
        "cases": [],
        "interactions": [
            {"channel": "Call", "direction": "Inbound", "days_ago": 12, "agent": "Ruth Okada", "subject": "Escrow question and homeowners", "duration_min": 9, "body": "I'm calling to check the escrow and principal balance on the home loan. Payments are on autopay and the service today was quick. I don't have homeowners with Northline. I'm open if the price is fair. Please send a quote when you can."},
        ],
    },
    {
        "id": "CUS-1003",
        "name": "Elena Vasquez",
        "age": 54,
        "city": "Miami",
        "region": "Florida",
        "occupation": "Hospital administrator",
        "email": "elena.vasquez@mail.example",
        "phone": "+1 (305) 555-0103",
        "segment": "Priority",
        "book": "Insurance",
        "tenure_months": 138,
        "customer_value": 96000,
        "story_kicker": "High-value retention",
        "story_title": "Eleven years on the book, advisor went quiet",
        "story_blurb": "Priority client. Beneficiary change is still open. She does not want a discount.",
        "products": [
            {"kind": "Policy", "name": "Whole life", "number": "POL-10031", "status": "Active", "installment": 8400, "frequency": "Annual", "cover": 1200000, "outstanding": 0, "renewal_in_days": 200, "started_days_ago": 4000, "pay": "annual2"},
            {"kind": "Policy", "name": "Homeowners", "number": "POL-10032", "status": "Active", "installment": 4200, "frequency": "Annual", "cover": 1850000, "outstanding": 0, "renewal_in_days": 110, "started_days_ago": 2200, "pay": "annual2"},
            {"kind": "Policy", "name": "Auto Preferred", "number": "POL-10033", "status": "Active", "installment": 1680, "frequency": "Annual", "cover": 500000, "outstanding": 0, "renewal_in_days": 70, "started_days_ago": 900, "pay": "annual2"},
            {"kind": "Policy", "name": "Umbrella", "number": "POL-10034", "status": "Active", "installment": 620, "frequency": "Annual", "cover": 2000000, "outstanding": 0, "renewal_in_days": 70, "started_days_ago": 900, "pay": "annual2"},
        ],
        "cases": [
            {"id": "SRV-1003", "kind": "Service", "title": "Beneficiary change not completed", "description": "Client asked for a beneficiary update on the whole life policy. Advisor has not completed the form.", "status": "In Progress", "opened_days_ago": 9, "closed_days_ago": None, "amount": None, "product_index": 0},
        ],
        "interactions": [
            {"channel": "Call", "direction": "Inbound", "days_ago": 4, "agent": "Chris Pell", "subject": "Beneficiary update still open", "duration_min": 12, "body": "I've been a client for eleven years and I'm disappointed. I asked for a simple beneficiary update and my advisor still hasn't called me back. I don't want a discount. I want someone to do what they said they would. This is poor service for a priority account."},
            {"channel": "Call", "direction": "Inbound", "days_ago": 160, "agent": "Chris Pell", "subject": "Annual priority review", "duration_min": 18, "body": "Thanks for the annual review. I'm pleased with the umbrella and the whole life illustration. Please keep everything as it is."},
        ],
    },
    {
        "id": "CUS-1175",
        "name": "Daniel Brooks",
        "age": 33,
        "city": "Denver",
        "region": "Colorado",
        "occupation": "Electrician",
        "email": "daniel.brooks@mail.example",
        "phone": "+1 (303) 555-0175",
        "segment": "Retail",
        "book": "Insurance",
        "tenure_months": 28,
        "customer_value": 4100,
        "story_kicker": "Healthy account",
        "story_title": "Paid claim, current premium, no outreach needed",
        "story_blurb": "Hail repair was paid. Last call was a thank-you. Renewal is not close.",
        "products": [
            {"kind": "Policy", "name": "Auto Comprehensive", "number": "POL-61751", "status": "Active", "installment": 128, "frequency": "Monthly", "cover": 300000, "outstanding": 0, "renewal_in_days": 210, "started_days_ago": 840, "pay": "monthly6"},
        ],
        "cases": [
            {"id": "CLM-6175", "kind": "Claim", "title": "Hail repair paid", "description": "Shop repair and rental were approved and paid. File closed.", "status": "Resolved", "opened_days_ago": 40, "closed_days_ago": 18, "amount": 2140, "product_index": 0},
        ],
        "interactions": [
            {"channel": "Call", "direction": "Inbound", "days_ago": 16, "agent": "Maya Feldman", "subject": "Thank you for the hail repair", "duration_min": 6, "body": "I wanted to thank the claims team. The repair shop you recommended was excellent and the rental car was ready the same day. I'm pleased with how the hail repair was handled."},
        ],
    },
    {
        "id": "CUS-1267",
        "name": "Sofia Alvarez",
        "age": 29,
        "city": "Phoenix",
        "region": "Arizona",
        "occupation": "Restaurant supervisor",
        "email": "sofia.alvarez@mail.example",
        "phone": "+1 (602) 555-0167",
        "segment": "Mass",
        "book": "Lending",
        "tenure_months": 18,
        "customer_value": 4200,
        "products": [
            {"kind": "Loan", "name": "Personal loan", "number": "LN-22671", "status": "Delinquent", "installment": 640, "frequency": "Monthly", "cover": 0, "outstanding": 18400, "renewal_in_days": None, "started_days_ago": 540, "pay": "monthly6-miss-1-2"},
        ],
        "cases": [],
        "interactions": [
            {"channel": "Call", "direction": "Inbound", "days_ago": 1, "agent": "Owen Blake", "subject": "Two missed installments", "duration_min": 10, "body": "I missed two payments because my hours were cut in August. I'm not trying to hide from you. I can pay half this Friday if you hold off on collections. I'm stressed about the late fees and I don't want the loan to charge off."},
        ],
    },
    {
        "id": "CUS-1066",
        "name": "Robert Hale",
        "age": 61,
        "city": "Providence",
        "region": "Rhode Island",
        "occupation": "Retired facilities manager",
        "email": "robert.hale@mail.example",
        "phone": "+1 (401) 555-0166",
        "segment": "Affluent",
        "book": "Insurance",
        "tenure_months": 96,
        "customer_value": 22400,
        "products": [
            {"kind": "Policy", "name": "Homeowners", "number": "POL-22041", "status": "Active", "installment": 2140, "frequency": "Annual", "cover": 740000, "outstanding": 0, "renewal_in_days": 130, "started_days_ago": 2500, "pay": "annual2"},
        ],
        "cases": [
            {"id": "CLM-2204", "kind": "Claim", "title": "Roof flashing denied as wear and tear", "description": "Denial issued for wear and tear versus storm damage. Customer disputes the finding.", "status": "Denied", "opened_days_ago": 34, "closed_days_ago": 18, "amount": 6400, "product_index": 0},
            {"id": "CMP-2205", "kind": "Complaint", "title": "Reinspection refused", "description": "Customer has asked twice for a reinspection and is preparing a complaint to the state insurance department.", "status": "Open", "opened_days_ago": 16, "closed_days_ago": None, "amount": 6400, "product_index": 0},
        ],
        "interactions": [
            {"channel": "Call", "direction": "Inbound", "days_ago": 2, "agent": "Lila Cho", "subject": "Denial and reinspection", "duration_min": 13, "body": "Your denial letter calls the roof wear and tear. The storm tore the flashing off. I've asked twice for a reinspection. If this isn't escalated I'm filing with the state insurance department. This is ridiculous."},
        ],
    },
    {
        "id": "CUS-1134",
        "name": "Aisha Rahman",
        "age": 47,
        "city": "Houston",
        "region": "Texas",
        "occupation": "Clinic owner",
        "email": "aisha.rahman@mail.example",
        "phone": "+1 (713) 555-0138",
        "segment": "SME",
        "book": "Insurance",
        "tenure_months": 54,
        "customer_value": 18600,
        "products": [
            {"kind": "Policy", "name": "Business owners policy", "number": "POL-81341", "status": "Active", "installment": 860, "frequency": "Monthly", "cover": 1000000, "outstanding": 0, "renewal_in_days": 100, "started_days_ago": 1500, "pay": "monthly6"},
        ],
        "cases": [
            {"id": "SRV-8134", "kind": "Service", "title": "Certificate of insurance outstanding", "description": "Landlord will not let a contractor start until the certificate of insurance is issued. Third request.", "status": "Open", "opened_days_ago": 16, "closed_days_ago": None, "amount": None, "product_index": 0},
        ],
        "interactions": [
            {"channel": "Call", "direction": "Inbound", "days_ago": 1, "agent": "Helena Ortiz", "subject": "Certificate of insurance", "duration_min": 7, "body": "This is the third request for the certificate of insurance our landlord needs. The building will not let the contractor start without it. It's frustrating that a one-page certificate is taking this long. Please call me today."},
        ],
    },
    {
        "id": "CUS-1255",
        "name": "Liam Murphy",
        "age": 31,
        "city": "Columbus",
        "region": "Ohio",
        "occupation": "Physical therapist",
        "email": "liam.murphy@mail.example",
        "phone": "+1 (614) 555-0155",
        "segment": "Retail",
        "book": "Insurance",
        "tenure_months": 8,
        "customer_value": 2400,
        "products": [
            {"kind": "Policy", "name": "Term Life 20", "number": "POL-92551", "status": "Active", "installment": 28, "frequency": "Monthly", "cover": 400000, "outstanding": 0, "renewal_in_days": 300, "started_days_ago": 240, "pay": "monthly6"},
        ],
        "cases": [],
        "interactions": [
            {"channel": "Email", "direction": "Inbound", "days_ago": 5, "agent": "Jonah Reed", "subject": "Accident rider before travel", "duration_min": None, "body": "We're leaving for Portugal in December. Could you add an accident rider to the term policy before we go? The new policy has been easy so far. I'm happy with the price."},
        ],
    },
    {
        "id": "CUS-1182",
        "name": "Hannah Berg",
        "age": 27,
        "city": "Portland",
        "region": "Oregon",
        "occupation": "Graphic designer",
        "email": "hannah.berg@mail.example",
        "phone": "+1 (503) 555-0182",
        "segment": "Retail",
        "book": "Insurance",
        "tenure_months": 14,
        "customer_value": 900,
        "products": [
            {"kind": "Policy", "name": "Travel protection", "number": "POL-71821", "status": "Active", "installment": 186, "frequency": "Annual", "cover": 8000, "outstanding": 0, "renewal_in_days": 160, "started_days_ago": 200, "pay": "annual2"},
        ],
        "cases": [
            {"id": "CLM-7182", "kind": "Claim", "title": "Trip interruption in Lisbon", "description": "Flight interruption expenses submitted. Customer asked for timing and said there is no rush.", "status": "Open", "opened_days_ago": 6, "closed_days_ago": None, "amount": 840, "product_index": 0},
        ],
        "interactions": [
            {"channel": "Email", "direction": "Inbound", "days_ago": 3, "agent": "Alicia Nguyen", "subject": "Status of the Lisbon claim", "duration_min": None, "body": "Checking on the travel claim for the flight that was cancelled in Lisbon. No rush at all. I just want the claim number and a rough timing. The trip cover itself has been fine."},
        ],
    },
    {
        "id": "CUS-1194",
        "name": "Kenji Sato",
        "age": 45,
        "city": "San Jose",
        "region": "California",
        "occupation": "Hardware engineer",
        "email": "kenji.sato@mail.example",
        "phone": "+1 (408) 555-0194",
        "segment": "Retail",
        "book": "Insurance",
        "tenure_months": 36,
        "customer_value": 5200,
        "products": [
            {"kind": "Policy", "name": "Auto Comprehensive", "number": "POL-61941", "status": "Active", "installment": 154, "frequency": "Monthly", "cover": 300000, "outstanding": 0, "renewal_in_days": 90, "started_days_ago": 1000, "pay": "monthly6"},
        ],
        "cases": [],
        "interactions": [
            {"channel": "Call", "direction": "Inbound", "days_ago": 15, "agent": "Samir Shah", "subject": "Renewal timing", "duration_min": 4, "body": "Confirming my auto policy renews in about three months. No changes and no claims. Thanks for the text reminder."},
        ],
    },
    {
        "id": "CUS-1148",
        "name": "Fatima Diallo",
        "age": 39,
        "city": "Minneapolis",
        "region": "Minnesota",
        "occupation": "Pharmacist",
        "email": "fatima.diallo@mail.example",
        "phone": "+1 (612) 555-0148",
        "segment": "Retail",
        "book": "Insurance",
        "tenure_months": 22,
        "customer_value": 3600,
        "products": [
            {"kind": "Policy", "name": "Health Advantage", "number": "POL-51481", "status": "Active", "installment": 164, "frequency": "Monthly", "cover": 15000, "outstanding": 0, "renewal_in_days": 180, "started_days_ago": 660, "pay": "monthly6-late-2"},
        ],
        "cases": [],
        "interactions": [
            {"channel": "Call", "direction": "Inbound", "days_ago": 20, "agent": "Ruth Okada", "subject": "Late fee reversed", "duration_min": 5, "body": "I'm calling to confirm the late fee on last month's premium was reversed. It was my mistake, the new card works, and I'm grateful you fixed it without a lecture."},
        ],
    },
    {
        "id": "CUS-1120",
        "name": "Oliver Grant",
        "age": 58,
        "city": "San Diego",
        "region": "California",
        "occupation": "Marine surveyor",
        "email": "oliver.grant@mail.example",
        "phone": "+1 (619) 555-0120",
        "segment": "Affluent",
        "book": "Insurance",
        "tenure_months": 84,
        "customer_value": 42000,
        "products": [
            {"kind": "Policy", "name": "Homeowners", "number": "POL-41201", "status": "Active", "installment": 3100, "frequency": "Annual", "cover": 1400000, "outstanding": 0, "renewal_in_days": 150, "started_days_ago": 2400, "pay": "annual2"},
            {"kind": "Policy", "name": "Auto Preferred", "number": "POL-41202", "status": "Active", "installment": 1480, "frequency": "Annual", "cover": 500000, "outstanding": 0, "renewal_in_days": 150, "started_days_ago": 900, "pay": "annual2"},
            {"kind": "Policy", "name": "Umbrella", "number": "POL-41203", "status": "Active", "installment": 540, "frequency": "Annual", "cover": 2000000, "outstanding": 0, "renewal_in_days": 150, "started_days_ago": 900, "pay": "annual2"},
        ],
        "cases": [
            {"id": "CLM-4120", "kind": "Claim", "title": "Water heater leak paid", "description": "Small water-heater leak paid two years ago. No residual issues.", "status": "Resolved", "opened_days_ago": 700, "closed_days_ago": 680, "amount": 980, "product_index": 0},
        ],
        "interactions": [
            {"channel": "Call", "direction": "Inbound", "days_ago": 25, "agent": "Chris Pell", "subject": "Annual review", "duration_min": 12, "body": "The annual review was smooth. Please keep the umbrella limit as it is and send the summary to my home address. No changes to the autos."},
        ],
    },
    {
        "id": "CUS-1201",
        "name": "Nina Kowalski",
        "age": 42,
        "city": "Chicago",
        "region": "Illinois",
        "occupation": "Bookkeeper",
        "email": "nina.kowalski@mail.example",
        "phone": "+1 (773) 555-0101",
        "segment": "Retail",
        "book": "Insurance",
        "tenure_months": 40,
        "customer_value": 3900,
        "products": [
            {"kind": "Policy", "name": "Auto Comprehensive", "number": "POL-32011", "status": "Active", "installment": 132, "frequency": "Monthly", "cover": 300000, "outstanding": 0, "renewal_in_days": 110, "started_days_ago": 1100, "pay": "monthly6"},
        ],
        "cases": [
            {"id": "CMP-3201", "kind": "Complaint", "title": "March premium billed twice", "description": "Duplicate draft was reversed. Refund to the card was approved.", "status": "Resolved", "opened_days_ago": 40, "closed_days_ago": 12, "amount": 132, "product_index": 0},
        ],
        "interactions": [
            {"channel": "Email", "direction": "Inbound", "days_ago": 6, "agent": "Maya Feldman", "subject": "Confirm the refund posted", "duration_min": None, "body": "Thank you for resolving the billing error on the March premium. Please check back next week to confirm the refund actually posted to my card. I'm pleased it was corrected."},
        ],
    },
    {
        "id": "CUS-1228",
        "name": "Carlos Mendes",
        "age": 51,
        "city": "Dallas",
        "region": "Texas",
        "occupation": "Fleet dispatcher",
        "email": "carlos.mendes@mail.example",
        "phone": "+1 (214) 555-0128",
        "segment": "Retail",
        "book": "Insurance",
        "tenure_months": 64,
        "customer_value": 9600,
        "products": [
            {"kind": "Policy", "name": "Auto Comprehensive", "number": "POL-82281", "status": "Lapsed", "installment": 168, "frequency": "Monthly", "cover": 300000, "outstanding": 0, "renewal_in_days": -25, "started_days_ago": 1800, "pay": "lapsed"},
        ],
        "cases": [],
        "interactions": [
            {"channel": "Email", "direction": "Inbound", "days_ago": 18, "agent": "Owen Blake", "subject": "Policy lapsed", "duration_min": None, "body": "I let the auto policy lapse last month after the premium jumped. I'm not angry. I just went with the other number. If you can match it for the next term I would look again."},
        ],
    },
    {
        "id": "CUS-1240",
        "name": "Grace Adeyemi",
        "age": 34,
        "city": "Charlotte",
        "region": "North Carolina",
        "occupation": "Pediatric nurse",
        "email": "grace.adeyemi@mail.example",
        "phone": "+1 (704) 555-0140",
        "segment": "Retail",
        "book": "Insurance",
        "tenure_months": 31,
        "customer_value": 4800,
        "products": [
            {"kind": "Policy", "name": "Health Advantage", "number": "POL-52401", "status": "Active", "installment": 172, "frequency": "Monthly", "cover": 15000, "outstanding": 0, "renewal_in_days": 200, "started_days_ago": 900, "pay": "monthly6"},
        ],
        "cases": [
            {"id": "CLM-5240", "kind": "Claim", "title": "Delivery admission paid", "description": "Hospital admission paid in four days. No balance outstanding.", "status": "Resolved", "opened_days_ago": 50, "closed_days_ago": 46, "amount": 4200, "product_index": 0},
        ],
        "interactions": [
            {"channel": "Call", "direction": "Inbound", "days_ago": 30, "agent": "Lila Cho", "subject": "Thank you for the hospital claim", "duration_min": 5, "body": "You paid the hospital claim in four days. I'm grateful. The nurses at the desk even said the pre-authorization was easy. Please keep the plan as it is."},
        ],
    },
    {
        "id": "CUS-1280",
        "name": "Wei Zhang",
        "age": 32,
        "city": "Irvine",
        "region": "California",
        "occupation": "Accountant",
        "email": "wei.zhang@mail.example",
        "phone": "+1 (949) 555-0180",
        "segment": "Retail",
        "book": "Lending",
        "tenure_months": 20,
        "customer_value": 6100,
        "products": [
            {"kind": "Loan", "name": "Auto loan", "number": "LN-32801", "status": "Active", "installment": 410, "frequency": "Monthly", "cover": 0, "outstanding": 18400, "renewal_in_days": None, "started_days_ago": 600, "pay": "monthly6"},
        ],
        "cases": [],
        "interactions": [
            {"channel": "Email", "direction": "Inbound", "days_ago": 9, "agent": "Jonah Reed", "subject": "GAP alternative", "duration_min": None, "body": "The dealer GAP policy on this auto loan is expensive. If Northline can cover the balance for less, please send a quote. Payments on your loan are current."},
        ],
    },
    {
        "id": "CUS-1292",
        "name": "Noah Williams",
        "age": 40,
        "city": "Raleigh",
        "region": "North Carolina",
        "occupation": "City planner",
        "email": "noah.williams@mail.example",
        "phone": "+1 (919) 555-0192",
        "segment": "Affluent",
        "book": "Lending",
        "tenure_months": 52,
        "customer_value": 27500,
        "products": [
            {"kind": "Loan", "name": "Home mortgage", "number": "LN-42921", "status": "Active", "installment": 2210, "frequency": "Monthly", "cover": 0, "outstanding": 356000, "renewal_in_days": None, "started_days_ago": 1500, "pay": "monthly6"},
        ],
        "cases": [],
        "interactions": [
            {"channel": "Call", "direction": "Inbound", "days_ago": 7, "agent": "Samir Shah", "subject": "Refinance question", "duration_min": 8, "body": "Can you refinance the mortgage if I move my checking over? Service has been smooth. I want to see the numbers before I talk to my credit union."},
        ],
    },
    {
        "id": "CUS-1304",
        "name": "Isabella Rossi",
        "age": 35,
        "city": "Philadelphia",
        "region": "Pennsylvania",
        "occupation": "Teacher",
        "email": "isabella.rossi@mail.example",
        "phone": "+1 (215) 555-0104",
        "segment": "Retail",
        "book": "Lending",
        "tenure_months": 26,
        "customer_value": 2800,
        "products": [
            {"kind": "Loan", "name": "Personal loan", "number": "LN-53041", "status": "Active", "installment": 280, "frequency": "Monthly", "cover": 0, "outstanding": 6200, "renewal_in_days": None, "started_days_ago": 780, "pay": "monthly6"},
            {"kind": "Policy", "name": "Credit life", "number": "POL-53042", "status": "Active", "installment": 18, "frequency": "Monthly", "cover": 6200, "outstanding": 0, "renewal_in_days": 250, "started_days_ago": 780, "pay": "monthly6"},
        ],
        "cases": [],
        "interactions": [
            {"channel": "Chat", "direction": "Inbound", "days_ago": 11, "agent": "Ruth Okada", "subject": "Autopay confirmation", "duration_min": None, "body": "Autopay went through again. Thanks. I don't need any changes."},
        ],
    },
    {
        "id": "CUS-1318",
        "name": "Samuel Boateng",
        "age": 49,
        "city": "Newark",
        "region": "New Jersey",
        "occupation": "Wholesale distributor",
        "email": "samuel.boateng@mail.example",
        "phone": "+1 (973) 555-0118",
        "segment": "SME",
        "book": "Both",
        "tenure_months": 41,
        "customer_value": 38000,
        "products": [
            {"kind": "Loan", "name": "SME term loan", "number": "LN-63181", "status": "Active", "installment": 6200, "frequency": "Monthly", "cover": 0, "outstanding": 480000, "renewal_in_days": None, "started_days_ago": 1200, "pay": "monthly6"},
            {"kind": "Policy", "name": "Business owners policy", "number": "POL-63182", "status": "Active", "installment": 740, "frequency": "Monthly", "cover": 1000000, "outstanding": 0, "renewal_in_days": 95, "started_days_ago": 1200, "pay": "monthly6"},
        ],
        "cases": [
            {"id": "SRV-6318", "kind": "Service", "title": "Annual covenant review", "description": "DSCR covenant watch. Year-end numbers were requested. Credit covenant review is due this month.", "status": "Open", "opened_days_ago": 5, "closed_days_ago": None, "amount": None, "product_index": 0},
        ],
        "interactions": [
            {"channel": "Email", "direction": "Inbound", "days_ago": 4, "agent": "Chris Pell", "subject": "Year-end numbers", "duration_min": None, "body": "Sending the year-end numbers your credit team asked for. Sales were softer in Q3 but we made payroll. Let me know if the package is complete."},
        ],
    },
    {
        "id": "CUS-1330",
        "name": "Chloe Martin",
        "age": 26,
        "city": "Nashville",
        "region": "Tennessee",
        "occupation": "Junior designer",
        "email": "chloe.martin@mail.example",
        "phone": "+1 (615) 555-0130",
        "segment": "Mass",
        "book": "Lending",
        "tenure_months": 21,
        "customer_value": 1600,
        "products": [
            {"kind": "Loan", "name": "Personal loan", "number": "LN-73301", "status": "Active", "installment": 640, "frequency": "Monthly", "cover": 0, "outstanding": 1900, "renewal_in_days": None, "started_days_ago": 630, "pay": "monthly6"},
        ],
        "cases": [],
        "interactions": [
            {"channel": "Call", "direction": "Inbound", "days_ago": 8, "agent": "Maya Feldman", "subject": "Credit life before payoff", "duration_min": 6, "body": "I have three installments left and then this personal loan is done. Last time you mentioned credit life. I'd like to hear the options before I pay it off. I'm happy with how simple the loan has been."},
        ],
    },
    {
        "id": "CUS-1344",
        "name": "David Kim",
        "age": 43,
        "city": "Fairfax",
        "region": "Virginia",
        "occupation": "Federal analyst",
        "email": "david.kim@mail.example",
        "phone": "+1 (703) 555-0144",
        "segment": "Affluent",
        "book": "Lending",
        "tenure_months": 70,
        "customer_value": 27000,
        "products": [
            {"kind": "Loan", "name": "Home mortgage", "number": "LN-83441", "status": "Delinquent", "installment": 3100, "frequency": "Monthly", "cover": 0, "outstanding": 510000, "renewal_in_days": None, "started_days_ago": 2100, "pay": "monthly6-miss-1"},
        ],
        "cases": [],
        "interactions": [
            {"channel": "Call", "direction": "Inbound", "days_ago": 3, "agent": "Owen Blake", "subject": "Missed mortgage draft", "duration_min": 7, "body": "I'm sorry I missed the draft on the mortgage. I was traveling and the backup card expired. I can pay the full installment this Friday. I'm worried this will hurt my credit, but I'm not disputing the amount. You've been fair with me."},
        ],
    },
    {
        "id": "CUS-1358",
        "name": "Amara Singh",
        "age": 46,
        "city": "Jersey City",
        "region": "New Jersey",
        "occupation": "Retail operations lead",
        "email": "amara.singh@mail.example",
        "phone": "+1 (201) 555-0158",
        "segment": "Affluent",
        "book": "Both",
        "tenure_months": 58,
        "customer_value": 64000,
        "products": [
            {"kind": "Loan", "name": "Property loan", "number": "LN-93581", "status": "Active", "installment": 2100, "frequency": "Monthly", "cover": 0, "outstanding": 240000, "renewal_in_days": None, "started_days_ago": 1700, "pay": "monthly6"},
            {"kind": "Policy", "name": "Term Life 20", "number": "POL-93582", "status": "Active", "installment": 96, "frequency": "Monthly", "cover": 800000, "outstanding": 0, "renewal_in_days": 260, "started_days_ago": 1000, "pay": "monthly6"},
        ],
        "cases": [],
        "interactions": [
            {"channel": "Call", "direction": "Inbound", "days_ago": 22, "agent": "Lila Cho", "subject": "Mid-year check-in", "duration_min": 8, "body": "The property loan is on track and the term policy is fine. No changes this year. Thanks for the fast payoff illustration last spring."},
        ],
    },
    {
        "id": "CUS-1371",
        "name": "Thomas Berger",
        "age": 52,
        "city": "Denver",
        "region": "Colorado",
        "occupation": "Brewery owner",
        "email": "thomas.berger@mail.example",
        "phone": "+1 (720) 555-0171",
        "segment": "Affluent",
        "book": "Insurance",
        "tenure_months": 77,
        "customer_value": 61000,
        "products": [
            {"kind": "Policy", "name": "Commercial auto", "number": "POL-13711", "status": "Active", "installment": 6400, "frequency": "Annual", "cover": 1000000, "outstanding": 0, "renewal_in_days": 80, "started_days_ago": 2000, "pay": "annual2"},
            {"kind": "Policy", "name": "Business owners policy", "number": "POL-13712", "status": "Active", "installment": 920, "frequency": "Monthly", "cover": 1500000, "outstanding": 0, "renewal_in_days": 80, "started_days_ago": 2000, "pay": "monthly6"},
        ],
        "cases": [],
        "interactions": [
            {"channel": "Email", "direction": "Inbound", "days_ago": 5, "agent": "Chris Pell", "subject": "Renewal price", "duration_min": None, "body": "I've started shopping around. The auto premium feels high compared with two numbers I got last week, and I'm disappointed nobody called me after my last email. Nothing is broken on the claim side. If you can sharpen the renewal price I will listen, otherwise I may not renew."},
        ],
    },
    {
        "id": "CUS-1386",
        "name": "Leila Haddad",
        "age": 28,
        "city": "Ann Arbor",
        "region": "Michigan",
        "occupation": "Graduate researcher",
        "email": "leila.haddad@mail.example",
        "phone": "+1 (734) 555-0186",
        "segment": "Retail",
        "book": "Insurance",
        "tenure_months": 2,
        "customer_value": 720,
        "products": [
            {"kind": "Policy", "name": "Renters", "number": "POL-13861", "status": "Active", "installment": 18, "frequency": "Monthly", "cover": 40000, "outstanding": 0, "renewal_in_days": 330, "started_days_ago": 60, "pay": "monthly6"},
        ],
        "cases": [
            {"id": "SRV-1386", "kind": "Service", "title": "Onboarding documents incomplete", "description": "Scheduled-items schedule was not uploaded. Onboarding is still open.", "status": "Open", "opened_days_ago": 12, "closed_days_ago": None, "amount": None, "product_index": 0},
        ],
        "interactions": [
            {"channel": "Email", "direction": "Inbound", "days_ago": 2, "agent": "Helena Ortiz", "subject": "Which documents are missing", "duration_min": None, "body": "I bought the renters policy two months ago and I'm confused about the portal. Which documents do you still need for the scheduled items? Please call me tomorrow after 4."},
        ],
    },
    {
        "id": "CUS-1008",
        "name": "Patrick O'Brien",
        "age": 63,
        "city": "Boston",
        "region": "Massachusetts",
        "occupation": "Retired attorney",
        "email": "patrick.obrien@mail.example",
        "phone": "+1 (617) 555-0108",
        "segment": "Priority",
        "book": "Both",
        "tenure_months": 168,
        "customer_value": 110000,
        "products": [
            {"kind": "Policy", "name": "Whole life", "number": "POL-10081", "status": "Active", "installment": 12600, "frequency": "Annual", "cover": 2000000, "outstanding": 0, "renewal_in_days": 160, "started_days_ago": 5000, "pay": "annual2"},
            {"kind": "Policy", "name": "Homeowners", "number": "POL-10082", "status": "Active", "installment": 5400, "frequency": "Annual", "cover": 2400000, "outstanding": 0, "renewal_in_days": 140, "started_days_ago": 3000, "pay": "annual2"},
            {"kind": "Policy", "name": "Umbrella", "number": "POL-10083", "status": "Active", "installment": 880, "frequency": "Annual", "cover": 5000000, "outstanding": 0, "renewal_in_days": 140, "started_days_ago": 2000, "pay": "annual2"},
            {"kind": "Loan", "name": "Pledged-asset line", "number": "LN-10084", "status": "Active", "installment": 1800, "frequency": "Monthly", "cover": 0, "outstanding": 250000, "renewal_in_days": None, "started_days_ago": 800, "pay": "monthly6"},
        ],
        "cases": [],
        "interactions": [
            {"channel": "Call", "direction": "Outbound", "days_ago": 19, "agent": "Chris Pell", "subject": "Quarterly review", "duration_min": 15, "body": "Quarterly review completed with the client. All four relationships were confirmed. He asked for the usual accountant letter, same as last year. No issues were raised."},
        ],
    },
    {
        "id": "CUS-1402",
        "name": "Yuki Tanaka",
        "age": 37,
        "city": "Sacramento",
        "region": "California",
        "occupation": "Landscape designer",
        "email": "yuki.tanaka@mail.example",
        "phone": "+1 (916) 555-0102",
        "segment": "Retail",
        "book": "Insurance",
        "tenure_months": 19,
        "customer_value": 3400,
        "products": [
            {"kind": "Policy", "name": "Homeowners", "number": "POL-14021", "status": "Active", "installment": 980, "frequency": "Annual", "cover": 620000, "outstanding": 0, "renewal_in_days": 175, "started_days_ago": 570, "pay": "annual2"},
        ],
        "cases": [
            {"id": "CLM-1402", "kind": "Claim", "title": "Water-damage invoice review", "description": "Invoice dates do not match the photo timestamps. The file is in special review and customer commitments are on hold.", "status": "In Progress", "opened_days_ago": 11, "closed_days_ago": None, "amount": 4200, "product_index": 0},
        ],
        "interactions": [
            {"channel": "Note", "direction": "Internal", "days_ago": 1, "agent": "Maya Feldman", "subject": "Desk note — hold commitments", "duration_min": None, "body": "Desk note: invoice dates do not match the photo timestamps. Hold customer commitments. File queued for special review. Do not estimate a payout."},
            {"channel": "Email", "direction": "Inbound", "days_ago": 4, "agent": "Maya Feldman", "subject": "What else do you need", "duration_min": None, "body": "I uploaded the photos and the repair invoice again. I don't understand why the claim is still open. Please tell me if something else is missing. I'm not upset. I just want a clear list."},
        ],
    },
]
